//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat_tbl()
        {
            this.Ticket_tbl = new HashSet<Ticket_tbl>();
        }
    
        public int KID { get; set; }
        public Nullable<int> KSeatNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_tbl> Ticket_tbl { get; set; }
    }
}
