//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoVan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_tbl
    {
        public int YID { get; set; }
        public string YName { get; set; }
        public Nullable<int> YAge { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<int> SeatID { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string KalkisYeri { get; set; }
        public string VarisYeri { get; set; }
        public string IletisimNo { get; set; }
    
        public virtual Seat_tbl Seat_tbl { get; set; }
    }
}
